primary:
  datasource:
    jdbcUrl: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
    username: postgres
    password: 111
secondary:
  datasource:
    jdbcUrl: jdbc:postgresql://localhost:5432/postgres?currentSchema=demo
    username: postgres
    password: 111